name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: "Build/Test"
      env:
        MKN_GCC_PREFERRED: 1
      run: |
        wget https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn_nix
        KLOG=3 ./mkn_nix clean build run -p test,bench -OtKda "-std=c++17 -fPIC" -l -pthread -g 0
