name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: "Build/Test"
      env:
        MKN_GCC_PREFERRED: 1
      run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        KLOG=3 ./mkn clean build run -p bench -OtKda "-std=c++20 -fPIC" -l -pthread -g 0
#KLOG=3 ./mkn clean build test -p test -OtKda "-std=c++20 -fPIC" -l -pthread -g 0

